# Generated by Django 3.2.9 on 2021-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_tablemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
