# Generated by Django 3.2.9 on 2021-11-24 04:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
