# Generated by Django 3.2.9 on 2021-11-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menumodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.categorymodel'),
        ),
    ]
