# Generated by Django 3.2.9 on 2021-11-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menumodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='restaurant.categorymodel'),
        ),
    ]
