# Generated by Django 3.2.9 on 2021-11-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menumodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.restaurant'),
        ),
    ]
